2018-08-23 15:57:09.890 [error] <0.408.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.413.0> exit with reason normal in context child_terminated
2018-08-23 15:57:14.191 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.176.0> exit with reason normal in context child_terminated
2018-08-23 15:57:18.060 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.176.0> exit with reason normal in context child_terminated
2018-08-23 15:57:19.323 [error] <0.532.0> gen_server test_1 terminated with reason: die
2018-08-23 15:57:19.324 [error] <0.532.0> CRASH REPORT Process test_1 with 0 neighbours exited with reason: die in gen_server:decode_msg/9 line 410
2018-08-23 15:57:30.343 [error] <0.404.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.409.0> exit with reason normal in context child_terminated
2018-08-23 15:57:34.045 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.176.0> exit with reason normal in context child_terminated
2018-08-23 15:57:39.235 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.176.0> exit with reason normal in context child_terminated
